### ISSUE TITLE
Github登陆失败

### ISSUE THREAD

**Issue by weilueluo** [itellyou-com/itellyou#1]
### 操作
1. 前往https://www.aomao.com/
2. 点击免费注册
3. 点击github图标

### 结果
URL
```
https://www.yanmao.cc/api/oauth/github/callback?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=85e53115-d31c-4d38-a4db-89dcba31539f
```
页面
![image](https://user-images.githubusercontent.com/39546701/178144258-43abb3ef-aa20-4392-aa6f-6861f4be0450.png)

**Comment by big-camel** [comment]
域名忘换了。。。

**Comment by weilueluo** [comment]
现在能连到Github了，但是返回网站后出现internal server error. https://www.aomao.com/500

**Comment by big-camel** [comment]
嗯，应该是api哪里出现了错误。可以使用其它方式登录注册，因为这个项目已经暂时没有维护了，我在做富文本相关领域的了。

**Comment by weilueluo** [comment]
嗯嗯好，没事
